#!/usr/bin/env python3
"""
Simple CGI script that displays a greeting page
"""

print("Content-Type: text/html")
print("Status: 200 OK")
print()  # Empty line separates headers from body

print("""<!DOCTYPE html>
<html>
<head>
    <title>Python CGI - Hello</title>
    <style>
        body {
            font-family: -apple-system, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .container {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 40px;
            box-shadow: 0 8px 32px rgba(0,0,0,0.3);
        }
        h1 { font-size: 48px; margin-bottom: 20px; }
        p { font-size: 18px; line-height: 1.6; }
        .badge {
            display: inline-block;
            background: rgba(255,255,255,0.2);
            padding: 8px 16px;
            border-radius: 20px;
            font-weight: bold;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🐍 Hello from Python CGI!</h1>
        <p>This page was generated by a Python script executed via CGI.</p>
        <p>Your Webserv server successfully:</p>
        <ul>
            <li>Forked a child process</li>
            <li>Executed the Python interpreter</li>
            <li>Captured the output</li>
            <li>Returned this HTML page</li>
        </ul>
        <div class="badge">✓ CGI Working!</div>
        <p style="margin-top: 30px;"><a href="/" style="color: white;">← Back to home</a></p>
    </div>
</body>
</html>""")